apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifications-db.fullname" . }}
  labels:
    {{- include "notifications-db.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.database.name | b64enc | quote }}
  POSTGRES_USER: {{ .Values.database.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc | quote }}
