{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bank-app.fullname" . }}-ingress
  labels:
    {{- include "bank-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/accounts
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-accounts-service
                port:
                  number: 8081
          - path: /api/cash
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-cash-service
                port:
                  number: 8082
          - path: /api/transfer
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-transfer-service
                port:
                  number: 8083
          - path: /api/notifications
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-notifications-service
                port:
                  number: 8084
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-auth-server
                port:
                  number: 9000
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-auth-server
                port:
                  number: 9000
          - path: /.well-known
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-auth-server
                port:
                  number: 9000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-front-ui
                port:
                  number: 8080
{{- end }}
