apiVersion: v1
kind: Service
metadata:
  name: {{ include "notifications-service.fullname" . }}
  labels:
    {{- include "notifications-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    {{- include "notifications-service.selectorLabels" . | nindent 4 }}
