server:
  port: 9000
  servlet:
    session:
      cookie:
        name: AUTHSESSIONID

spring:
  application:
    name: auth-server

auth:
  issuer-uri: ${AUTH_ISSUER_URI:http://localhost:9000}
  front-ui-redirect-uri: ${FRONT_UI_REDIRECT_URI:http://localhost:8080/login/oauth2/code/front-ui-client}

logging:
  level:
    root: ${LOG_LEVEL:WARN}
    com.bank: ${LOG_LEVEL:INFO}
