server:
  port: 8080

spring:
  application:
    name: front-ui
  config:
    import: "optional:configserver:"
  security:
    oauth2:
      client:
        registration:
          front-ui-client:
            provider: auth-server
            client-id: front-ui-client
            client-secret: front-ui-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,accounts,cash,transfer
        provider:
          auth-server:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            user-info-uri: http://localhost:9000/userinfo
            user-name-attribute: sub

gateway:
  url: http://localhost:9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
