server:
  port: 8080

spring:
  application:
    name: front-ui
  security:
    oauth2:
      client:
        registration:
          front-ui-client:
            provider: auth-server
            client-id: ${OAUTH2_CLIENT_ID:front-ui-client}
            client-secret: ${OAUTH2_CLIENT_SECRET:front-ui-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,accounts,cash,transfer
        provider:
          auth-server:
            authorization-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTHSERVER_AUTHORIZATIONURI:http://localhost:9000/oauth2/authorize}
            token-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTHSERVER_TOKENURI:http://localhost:9000/oauth2/token}
            jwk-set-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTHSERVER_JWKSETURI:http://localhost:9000/oauth2/jwks}
            user-info-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTHSERVER_USERINFOURI:http://localhost:9000/userinfo}
            user-name-attribute: sub

services:
  accounts:
    url: ${ACCOUNTS_SERVICE_URL:http://localhost:8081}
  cash:
    url: ${CASH_SERVICE_URL:http://localhost:8082}
  transfer:
    url: ${TRANSFER_SERVICE_URL:http://localhost:8083}

logging:
  level:
    root: ${LOG_LEVEL:WARN}
    com.bank: ${LOG_LEVEL:INFO}
