apiVersion: v1
kind: Service
metadata:
  name: {{ include "accounts-db.fullname" . }}
  labels:
    {{- include "accounts-db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    {{- include "accounts-db.selectorLabels" . | nindent 4 }}
